---
name: Fetch and build Greenscore
description: Fetch and build the greenscore
inputs:
  token:
    description: 'The token to use for fetching the repository'
    required: true
  branch:
    description: 'The branch to fetch for greenscore content'
    required: false
    default: 'ci/deploy'
    # default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.branch }}
        token: ${{ inputs.token }}
        path: sustainability-portal/

    # - name: Install Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '22'
    #     cache: 'npm'
    #     cache-dependency-path: sustainability-portal/package-lock.json

    # - name: Install dependencies
    #   shell: bash
    #   run: |
    #     cd sustainability-portal/
    #     npm install

    # - name: Build project
    #   shell: bash
    #   run: |
    #     cd sustainability-portal/
    #     npm run build

    - name: Copy build files
      shell: bash
      run: |
        mkdir -p public/
        # cp -r sustainability-portal/dist/* public/

        # Temporary. Waiting for the Sustainability Portal to be ready
        cp -r sustainability-portal/index.html public/
