---
name: Fetch and build Landscape
description: Fetch and build the landscape
inputs:
  token:
    description: 'The token to use for fetching the repository'
    required: true
  branch:
    description: 'The branch to fetch for landscape content'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: 'zatsit-oss/sustainability-landscape'
        ref: ${{ inputs.branch }}
        token: ${{ inputs.token }}
        path: landscape/

    - name: Download landscape2
      shell: bash
      run: |
        sudo apt install -y jq
        version=$(curl -s https://api.github.com/repos/cncf/landscape2/releases/latest | jq -r '.tag_name')
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cncf/landscape2/releases/download/${version}/landscape2-installer.sh | sh

    - name: Build landscape
      shell: bash
      run: |
        cd landscape/
        landscape2 build \
          --data-file zats-sustainability.yml \
          --settings-file settings.yml \
          --guide-file guide.yml \
          --logos-path logos \
          --output-dir build

    - name: Copy build files
      shell: bash
      run: |
        mkdir -p public/landscape
        cp -r landscape/build/* public/landscape/
