---
name: Validate

on:
  pull_request:
    paths:
      - "logos/**"
      - "guide.yml"
      - "settings.yml"
      - "zats-sustainability.yml"

jobs:
  validate-landscape-data:
    runs-on: ubuntu-latest
    name: "Validate landscape data file"
    steps:
      - uses: actions/checkout@v3
      - uses: cncf/landscape2-validate-action@v2
        with:
          target_kind: data
          target_path: ./zats-sustainability.yml

  validate-landscape-settings:
    runs-on: ubuntu-latest
    name: "Validate landscape settings file"
    steps:
      - uses: actions/checkout@v3
      - uses: cncf/landscape2-validate-action@v2
        with:
          target_kind: settings
          target_path: ./settings.yml

  validate-landscape-guide:
    runs-on: ubuntu-latest
    name: "Validate landscape guide file"
    steps:
      - uses: actions/checkout@v3
      - uses: cncf/landscape2-validate-action@v2
        with:
          target_kind: guide
          target_path: ./guide.yml
