---
name: Publish Greenscore Content

on:
  push:
    branches:
      - main
    paths:
      - "logos/**"
      - "guide.yml"
      - "settings.yml"
      - "zats-sustainability.yml"
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (production, staging)'
        required: true
        default: production

permissions:
  checks: write
  contents: read

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  environment: ${{ github.event.inputs.env || 'production' }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: kanga333/variable-mapper@master
        with:
          key: "${{ env.environment }}"
          map: |
            {
              "production": {
                "google_project_id": "${{ vars.GOOGLE_PROJECT_ID_PROD }}",
                "bucket_name": "${{ vars.GCS_BUCKET_NAME_PROD }}",
                "service_account__secret_name": "GOOGLE_STORAGE_SERVICE_ACCOUNT_ZATSIT_GREENSCORE_PROD"
              },
              "staging": {
                "google_project_id": "${{ vars.GOOGLE_PROJECT_ID_DEV }}",
                "bucket_name": "${{ vars.GCS_BUCKET_NAME_STAGING }}",
                "service_account__secret_name": "GOOGLE_STORAGE_SERVICE_ACCOUNT_ZATSIT_GREENSCORE_STAGING"
              }
            }

      - name: Fetch and Build greenscore content
        uses: ./.github/actions/astro
        with:
          token: ${{ secrets.GH_PAT }}
          branch: ${{ github.head_ref || github.ref_name }}

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.google_project_id }}
          credentials_json: ${{ secrets[env.service_account__secret_name] }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Clean Google Storage files
        run: |
          touch dummy.txt
          gsutil -q cp dummy.txt gs://${{ env.bucket_name }}/
          gsutil -q -m rm -r -f gs://${{ env.bucket_name }}/*
          rm dummy.txt

      - name: Upload to Cloud Storage
        id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'landing-page/dist/'
          destination: ${{ env.bucket_name }}
          parent: false
          gzip: falseq

      # needed to avoid the post action error
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
